version: '3'

services:
  postgres:
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - ./teste.sql:/docker-entrypoint-initdb.d/teste.sql
